name: OpenBench Build
on:
  push:
    branches: 
      - 55* 
  workflow_dispatch:

jobs:
  build_and_archive:
    name: Build and Archive
    strategy:
      matrix:
        os: [ubuntu-latest]
        nnue_flags: [avx2, avx512]
        cpu_flags: [popcnt, pext]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Linux GCC ${{ matrix.version }}
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x86
    - name: Clone Noggenfogger
      uses: actions/checkout@v3
    - name: Build Noggenfogger ${{ matrix.flags }}
      run: make build
    - name: Archive ${{ matrix.nnue_flags }}-${{ matrix.cpu_flags }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.sha }}-linux-${{ matrix.nnue_flags }}-${{ matrix.cpu_flags }}
        path: noggenfogger
